github: kiwinatra
patreon: kiwinatra
open_collective: eaglercraft
ko_fi: kiwinatra_love
tidelift: 
community_bridge: 
liberapay: kiwinatra
issuehunt: kiwinatra
lfx_crowdfunding: 
polar: kiwinatra
buy_me_a_coffee: kiwinatra_love
thanks_dev: kiwinatr3xx
custom: ['https://t.me/nanomi_suan', 'https://kiwinatra.github.io']
